site :opscode

cookbook 'apt'
cookbook 'apache2'
cookbook 'vim'
cookbook 'build-essential'
cookbook 'drush', git: 'https://github.com/msonnabaum/chef-drush'
cookbook 'git'
cookbook 'imagemagick'
cookbook 'mysql'
cookbook 'openssl'
cookbook 'php'
#cookbook 'discovery', git: 'git://github.com/hw-cookbooks/discovery.git'
cookbook 'redis', git: 'git://github.com/miah/chef-redis.git'
#cookbook 'redisio', git: 'git://github.com/brianbianco/redisio.git'
cookbook 'varnish'
