#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

cookbook 'apache2',
  :git => 'https://github.com/cookbooks/apache2'
cookbook 'apt',
  :git => 'https://github.com/cookbooks/apt'
cookbook 'build-essential',
  :git => 'https://github.com/cookbooks/build-essential'
cookbook 'drush',
  :git => 'https://github.com/msonnabaum/chef-drush'
cookbook 'git',
  :git => 'https://github.com/cookbooks/git'
cookbook 'imagemagick',
  :git => 'https://github.com/cookbooks/imagemagick'
cookbook 'mysql',
  :git => 'https://github.com/cookbooks/mysql'
cookbook 'openssl',
  :git => 'https://github.com/cookbooks/openssl'
cookbook 'php',
  :git => 'https://github.com/cookbooks/php'
cookbook 'redis',
  :git => 'https://github.com/cookbooks/redis'
cookbook 'varnish',
  :git => 'https://github.com/cookbooks/varnish'
